// src/components/layout/ScrollManager.svelte
<script lang="ts">
	import {
		BANNER_HEIGHT,
		BANNER_HEIGHT_HOME,
		MAIN_PANEL_OVERLAPS_BANNER_HEIGHT,
		NAVBAR_HEIGHT,
	} from "@constants/constants";
	import { onMount } from "svelte";
	import { siteConfig } from "@/config";

	// State variables
	let scrollTop = $state(0);
	let isHome = $state(false);
	let windowWidth = $state(1024);
	let windowHeight = $state(768);

	const bannerEnabled = siteConfig.banner.enable;

	// Derived values - automatically recompute when dependencies change
	const bannerHeight = $derived(
		windowHeight *
			((isHome && windowWidth >= 1024
				? BANNER_HEIGHT_HOME
				: BANNER_HEIGHT) /
				100),
	);

	const navbarThreshold = $derived(
		bannerHeight -
			NAVBAR_HEIGHT -
			MAIN_PANEL_OVERLAPS_BANNER_HEIGHT * 16 -
			16,
	);

	const isScrolledPastBanner = $derived(scrollTop > bannerHeight);
	const shouldShowNavbarHidden = $derived(scrollTop >= navbarThreshold);

	// Optimized element visibility toggler using classList.toggle
	function updateElementVisibility(
		element: HTMLElement | null,
		shouldShow: boolean,
		showClass = "",
		hideClass = "",
	) {
		if (!element) return;

		if (hideClass) element.classList.toggle(hideClass, !shouldShow);
		if (showClass) element.classList.toggle(showClass, shouldShow);
	}

	// Single $effect for all DOM updates - runs when dependencies change
	$effect(() => {
		if (typeof document === "undefined") return;

		const backToTopBtn = document.getElementById("back-to-top-btn");
		const toc = document.getElementById("toc-wrapper");
		const navbar = document.getElementById("navbar-wrapper");

		// Update back to top button (always)
		updateElementVisibility(backToTopBtn, isScrolledPastBanner, "", "hide");

		// Update TOC and navbar (only if banner is enabled)
		if (bannerEnabled) {
			updateElementVisibility(toc, isScrolledPastBanner, "", "toc-hide");
			updateElementVisibility(
				navbar,
				shouldShowNavbarHidden,
				"navbar-hidden",
				"",
			);
		}
	});

	// Event handlers - throttle not needed due to passive listeners and minimal work
	function handleScroll() {
		scrollTop =
			document.documentElement.scrollTop || document.body.scrollTop;
		isHome = document.body.classList.contains("is-home");
	}

	function handleResize() {
		windowWidth = window.innerWidth;
		windowHeight = window.innerHeight;
	}

	onMount(() => {
		// Initialize state from DOM
		handleResize();
		handleScroll();

		// Add passive event listeners for better performance
		window.addEventListener("scroll", handleScroll, { passive: true });
		window.addEventListener("resize", handleResize, { passive: true });

		return () => {
			window.removeEventListener("scroll", handleScroll);
			window.removeEventListener("resize", handleResize);
		};
	});
</script>

// src/components/layout/ScrollManager.tsx
import {
	component$,
	useComputed$,
	useSignal,
	useVisibleTask$,
} from "@builder.io/qwik";
import {
	BANNER_HEIGHT,
	BANNER_HEIGHT_HOME,
	MAIN_PANEL_OVERLAPS_BANNER_HEIGHT,
	NAVBAR_HEIGHT,
} from "@constants/constants";
import { siteConfig } from "@/config";

export default component$(() => {
	const bannerEnabled = siteConfig.banner.enable;

	// State variables
	const scrollTop = useSignal(0);
	const isHome = useSignal(false);
	const windowWidth = useSignal(1024);
	const windowHeight = useSignal(768);

	// Derived values - automatically recompute when dependencies change
	const bannerHeight = useComputed$(() => {
		return (
			windowHeight.value *
			((isHome.value && windowWidth.value >= 1024
				? BANNER_HEIGHT_HOME
				: BANNER_HEIGHT) /
				100)
		);
	});

	const navbarThreshold = useComputed$(() => {
		return (
			bannerHeight.value -
			NAVBAR_HEIGHT -
			MAIN_PANEL_OVERLAPS_BANNER_HEIGHT * 16 -
			16
		);
	});

	const isScrolledPastBanner = useComputed$(
		() => scrollTop.value > bannerHeight.value,
	);
	const shouldShowNavbarHidden = useComputed$(
		() => scrollTop.value >= navbarThreshold.value,
	);

	// biome-ignore lint/correctness/noQwikUseVisibleTask: Required for DOM manipulation based on scroll state
	useVisibleTask$(({ track }) => {
		// Track state changes
		track(() => isScrolledPastBanner.value);
		track(() => shouldShowNavbarHidden.value);

		if (typeof document === "undefined") return;

		const backToTopBtn = document.getElementById("back-to-top-btn");
		const toc = document.getElementById("toc-wrapper");
		const navbar = document.getElementById("navbar-wrapper");

		// Update back to top button (always)
		if (backToTopBtn) {
			backToTopBtn.classList.toggle("hide", !isScrolledPastBanner.value);
		}

		// Update TOC and navbar (only if banner is enabled)
		if (bannerEnabled) {
			if (toc) {
				toc.classList.toggle("toc-hide", !isScrolledPastBanner.value);
			}
			if (navbar) {
				navbar.classList.toggle("navbar-hidden", shouldShowNavbarHidden.value);
			}
		}
	});

	// biome-ignore lint/correctness/noQwikUseVisibleTask: Required for window event listeners
	useVisibleTask$(() => {
		// Event handlers
		const handleScroll = () => {
			scrollTop.value =
				document.documentElement.scrollTop || document.body.scrollTop;
			isHome.value = document.body.classList.contains("is-home");
		};

		const handleResize = () => {
			windowWidth.value = window.innerWidth;
			windowHeight.value = window.innerHeight;
		};

		// Initialize state from DOM
		handleResize();
		handleScroll();

		// Add event listeners with passive option for better performance
		window.addEventListener("scroll", handleScroll, { passive: true });
		window.addEventListener("resize", handleResize, { passive: true });

		return () => {
			window.removeEventListener("scroll", handleScroll);
			window.removeEventListener("resize", handleResize);
		};
	});

	return null;
});
